<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.lucky</groupId>
        <artifactId>lucky-modules</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>lucky-generator</artifactId>

    <description>
        generator代码生成
    </description>

    <dependencies>

        <!-- common 核心模块 -->
        <dependency>
            <groupId>com.lucky</groupId>
            <artifactId>lucky-common-core</artifactId>
        </dependency>

        <!-- common 日志模块 -->
        <dependency>
            <groupId>com.lucky</groupId>
            <artifactId>lucky-common-log</artifactId>
        </dependency>

        <!-- common Mybatis 模块 -->
        <dependency>
            <groupId>com.lucky</groupId>
            <artifactId>lucky-common-mybatis</artifactId>
        </dependency>

        <!-- common redis 模块 -->
        <dependency>
            <groupId>com.lucky</groupId>
            <artifactId>lucky-common-redis</artifactId>
        </dependency>

        <!-- common security 模块 -->
        <dependency>
            <groupId>com.lucky</groupId>
            <artifactId>lucky-common-security</artifactId>
        </dependency>

        <!-- common Web 模块 -->
        <dependency>
            <groupId>com.lucky</groupId>
            <artifactId>lucky-common-web</artifactId>
        </dependency>

        <!-- velocity代码生成使用模板 -->
        <dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity-engine-core</artifactId>
        </dependency>

    </dependencies>

</project>