<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.lucky</groupId>
        <artifactId>lucky-vue</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <modules>
        <module>lucky-common-bom</module>
        <module>lucky-common-core</module>
        <module>lucky-common-excel</module>
        <module>lucky-common-log</module>
        <module>lucky-common-mybatis</module>
        <module>lucky-common-redis</module>
        <module>lucky-common-security</module>
        <module>lucky-common-web</module>
    </modules>

    <artifactId>lucky-common</artifactId>
    <packaging>pom</packaging>

    <description>
        common 通用模块
    </description>

</project>