<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.lucky</groupId>
        <artifactId>lucky-modules</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>lucky-ai</artifactId>

    <description>
        ai大模型服务
    </description>

    <dependencies>

        <!-- common Mybatis 模块 -->
        <dependency>
            <groupId>com.lucky</groupId>
            <artifactId>lucky-common-mybatis</artifactId>
        </dependency>

        <!-- common 日志模块 -->
        <dependency>
            <groupId>com.lucky</groupId>
            <artifactId>lucky-common-log</artifactId>
        </dependency>

        <!-- common Excel 模块 -->
        <dependency>
            <groupId>com.lucky</groupId>
            <artifactId>lucky-common-excel</artifactId>
        </dependency>

        <!-- common Web 模块 -->
        <dependency>
            <groupId>com.lucky</groupId>
            <artifactId>lucky-common-web</artifactId>
        </dependency>

        <!-- common AI 模块 -->
        <dependency>
            <groupId>com.lucky</groupId>
            <artifactId>lucky-common-ai</artifactId>
        </dependency>

    </dependencies>

</project>